import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import BackToTop from "@/components/BackToTop";
import NextTopLoader from "nextjs-toploader";
import { SettingsProvider } from "@/context/SettingContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        <SettingsProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <NextTopLoader
              height={4}
              color='#00bc7e'
              shadow={false}
              showSpinner={false}
            />
            <Header />
            <main>{children}</main>
            <Footer />
            <BackToTop />
          </ThemeProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
