export const LANGUAGES = [
  { name: "العربية", flag: "sa" },
  { name: "简体中文", flag: "cn" },
  { name: "Nederlands", flag: "nl" },
  { name: "English", flag: "gb" },
  { name: "Français", flag: "fr" },
  { name: "Deutsch", flag: "de" },
  { name: "हिन्दी", flag: "in" },
  { name: "עברית", flag: "il" },
  { name: "Italiano", flag: "it" },
  { name: "Indonesia", flag: "id" },
  { name: "日本語", flag: "jp" },
  { name: "한국어", flag: "kr" },
  { name: "Melayu", flag: "my" },
  { name: "Polski", flag: "pl" },
  { name: "Português", flag: "pt" },
  { name: "فارسی", flag: "ir" },
  { name: "Română", flag: "ro" },
  { name: "Русский", flag: "ru" },
  { name: "Español", flag: "es" },
  { name: "Svenska", flag: "se" },
  { name: "ไทย", flag: "th" },
  { name: "Türkçe", flag: "tr" },
  { name: "Українська", flag: "ua" },
  { name: "Tiếng Việt", flag: "vn" },
];

export const QUALITIES = ["720p", "360p", "1080p", "1440p", "2160p", "2320p"];
